@startuml ChatbotDataBase

object "Chat" as chat {
  ChatID : string
  title: string
  date: date
  
}

object "Message" as message {
  int MessageID
  string MessageContent
  string PropmtContent
  int ChatID
  date MessageDate
  Usefulness Usefulness
}

object Usefulness {
    Useful
    NotUseful
    NotRated
}

object "PDF" as pdf {
  PDFID: int
  PDFContent: string
  PDFVectorized: Array<number>
  date: date
}

chat "1"----"*" message: Contains


@enduml