@startuml "Diagrama de secuencia de Monitor web"

actor "Usuario Interno" as Usuario
participant "DBMangerFrontend" as Monitor
participant "DBMangerBackend" as Backend
participant "AccouRateNginx" as Nginx
participant "MySQL" as MySQL

Usuario -> Monitor: Visualizar KPIs de la base de datos
Monitor -> Backend: GET /kpis
Backend -> Nginx: SQL Query
Nginx -> MySQL: SQL Query
MySQL -> Nginx: KPIs
Nginx -> Backend: KPIs
Backend -> Monitor: KPIs
Monitor -> Usuario: KPIs

@enduml