@startuml "Diagrama de Componentes"



cloud {
    [OVH] 
    package "AccouRateNginx" {
        folder "AccouRateBackend" {
            [Express]
        }
        database "AccouRateDatabase"{
            [MySQL]
        }
        folder "Docker" #LightBlue {
            [Pdf Generator] #LightBlue
            [Company Validator] #LightBlue
        }
    }
}

cloud {
    package "ChatBotNginx" #LightBlue {
        folder "ChatBotBackend" #LightBlue {
            [Flask] #LightBlue
        }
        database "Chatbot Database" #LightBlue {
            [MongoDB] #LightBlue
        }
    }
}

package "API Gateway" {
    [Nginx Gateway]
}

package "ThirdPartyDatabase"  {
    [Eikon]
    [Sabi]
}

package "AccourateFrontend" #LightBlue {
    [React] #LightBlue
}

package "MonitorWeb" #LightBlue {
    [MonitorWeb Backend] #LightBlue
    [MonitorWeb Frontend] #LightBlue
}

actor "User" as User
actor "Internal User" as InternalUser

User --> [AccourateFrontend] : KeyBoard, Mouse
InternalUser --> [MonitorWeb] : KeyBoard, Mouse

[Express] --> [AccouRateDatabase] 
[Express] --> [Docker] 
[Express] --> [ThirdPartyDatabase] : HTTP/HTTPS

[AccouRateNginx] --> [OVH]
[API Gateway] --> [OVH] : HTTP/HTTPS

[MonitorWeb Frontend] --> [MonitorWeb Backend] : Local Connection
[MonitorWeb Backend] --> [OVH] : HTTP/HTTPS

[AccourateFrontend] --> [API Gateway] : HTTP/HTTPS
[API Gateway] --> [ChatBotNginx] : HTTP/HTTPS
[ChatBotBackend] --> [Chatbot Database] : HTTP/HTTPS
[ChatBotNginx] --> [OVH] : HTTP/HTTPS

@enduml
