@startuml "Diagrama de secuencia de Chatbot"

actor "Usuario" as Usuario
participant "AccouRateFrontend" as web
participant "APIGateway" as APIGateway
participant "AssitantNginx" as Nginx
participant "AssitantBackend" as Chatbot
participant "Ollama" as Ollama
participant "MongoDB" as MongoDB


Usuario -> web: Subir un pdf
web -> APIGateway: POST /pdf
APIGateway -> Nginx: POST /pdf
Nginx -> Chatbot: POST /pdf
Chatbot -> Ollama: POST /embeding
Ollama -> Chatbot: Embedings
Chatbot -> MongoDB: Guardar pdf y embedings
Chatbot -> Usuario: 200 OK

Usuario -> web: Hace una consulta a los pdf subidos
web -> Chatbot: POST /query {consulta}
Chatbot -> Ollama: POST /embeding
Ollama -> Chatbot: Embedings
Chatbot -> MongoDB: Busca por similitud
MongoDB -> Chatbot: Documentos similares
Chatbot -> Ollama: POST /api/chat
Ollama -> Chatbot: Respuesta
Chatbot -> Usuario: Respuesta

@enduml