@startuml "Diagrama de Componentes"

cloud {
    [OVH]
    package "Nginx" {
        folder "Node Js"{
            [Express]
        }
        database "MySql" {
            [Database]
        }

        folder "Docker"{
            [Pdf Generator]
            [Company Validator]

        }
    }
}

cloud {
    package "Assistant Server" {
        folder "Flask Server" {
            [Assistant Controller]
        }
        database "MongoDB" {
            [Assistant Database]
        }
    }
}

package "API Gateway" {
    [Nginx Gateway]
}

package "External Database" {
    [Eikon]
    [Sabi]
}

package "Web Browser" {
    [Web React]
}



package "Internal Web Browser" {
    [DBManager Backend]
    [DBManager Frontend]
}



actor "User" as User
actor "Internal User" as InternalUser

User --> [Web Browser] : KeyBoard, Mouse
InternalUser --> [Internal Web Browser] : KeyBoard, Mouse
[Express] <--> [Database]: Local Connection
[Express] <--> [Docker]: Local Connection
[Express] <--> [External Database]: API Connection
[Nginx] <--> [OVH]
[API Gateway] <--> [OVH]: HTTP/HTTPS
[DBManager Frontend] <--> [DBManager Backend]: Local Connection
[DBManager Backend] <--> [OVH]: HTTP/HTTPS
[Web Browser] <--> [API Gateway]: HTTP/HTTPS
[API Gateway] <--> [Assistant Server]: HTTP/HTTPS
[Assistant Server] <--> [OVH]: HTTP/HTTPS