@startuml "Diagrama de secuencia de generación de informe"

actor "Usuario" as Usuario
participant "AccouRateFrontend" as N
participant "APIGateWay" as S
participant "AccouRateNginx" as Nginx 
participant "AccouRateBackend" as Express
participant "AccouRateDatabase" as MySQL
participant "PDF Generator" as PDF

alt "Usuario autenticado"
    Usuario -> N: Click en botón "Generar informe"
    N -> S: Petición POST /pdf
    S -> Nginx: Petición POST /pdf
    Nginx -> Express: Petición POST /pdf
    Express -> MySQL: Obtener datos compañia 
    MySQL -> Express: Datos 
    Express -> PDF: POST /pdf {datos}
    PDF -> PDF: GET /generate_pdf {datos}
    PDF -> Express: informe.pdf
    Express -> Nginx: informe.pdf
    Nginx -> S: informe.pdf
    S -> N: informe.pdf
else "Usuario con credenciales caducados"
    Usuario -> N: Click en botón "Generar informe"
    N -> S: Petición POST /pdf
    S -> Nginx: Petición POST /pdf
    Nginx -> Express: Petición POST /pdf
    Express -> Nginx: Error 401
    Nginx -> S: Error 401
    S -> N: Error 401
    N -> N: Redirigir a /login
end



@enduml