@startuml "Diagrama de Componentes"

cloud {
    [OVH]
    package "AccouRateNginx" {
        folder "AccouRateBackend" {
            [Express]
        }
        database "AccouRateDatabase" {
            [MySQL]
        }
        folder "Docker" {
            [Pdf Generator]
            [Company Validator]
        }
    }
}

cloud {
    package "AssistantNginx" {
        folder "AssistantBackend" {
            [Flask]
        }
        database "Assistant Database" {
            [MongoDB]
        }
    }
}

package "API Gateway" {
    [Nginx Gateway]
}

package "ThirdPartyDatabase" {
    [Eikon]
    [Sabi]
}

package "AccourateFrontend" {
    [React]
}

package "DBManager" {
    [DBManager Backend]
    [DBManager Frontend]
}

actor "User" as User
actor "Internal User" as InternalUser

User --> [AccourateFrontend] : KeyBoard, Mouse
InternalUser --> [DBManager] : KeyBoard, Mouse

[Express] --> [AccouRateDatabase] 
[Express] --> [Docker] 
[Express] --> [ThirdPartyDatabase] : HTTP/HTTPS

[AccouRateNginx] --> [OVH]
[API Gateway] --> [OVH] : HTTP/HTTPS

[DBManager Frontend] --> [DBManager Backend] : Local Connection
[DBManager Backend] --> [OVH] : HTTP/HTTPS

[AccourateFrontend] --> [API Gateway] : HTTP/HTTPS
[API Gateway] --> [AssistantNginx] : HTTP/HTTPS
[AssistantBackend] --> [Assistant Database] : HTTP/HTTPS
[AssistantNginx] --> [OVH] : HTTP/HTTPS

@enduml
