@startuml EsquemaNavegacion
left to right direction

[*] --> login
login --> principal
principal --> proyecto
proyecto --> compania
principal --> compania
compania --> analisisFinanciero
analisisFinanciero --> dashboard
analisisFinanciero --> peers
compania --> cashflow
cashflow --> peersMultiple
cashflow --> dcf
compania --> valoracion
compania --> esg


@enduml