@startuml "Modelo Conceptual Chatbot"

object Chat {
    <u>string: chatId
    string: chatName
}

object Message {
    <u>string: messageId
    string: userMessage
    string: promptMessage
    data: date
    USEFULNESS: usefulness
}

object PDF {
    <u>string: pdfId
    string: pdfName
    string: pdfContent
    numbers: embeddings
}

object USEFULNESS {
    USEFUL
    NOTUSEFUL
    NOTRATED
}

Chat "1" -- "N" Message

@enduml