@startuml "ModeloConceptualAccouRateFrontend"

object User {
    <u>string: userId
    string: username
    string: password
    string: email
    Role: role
    License: license
}

object License {
    <u>string: licenseId
    string: licenseName
    int: maxProjects
    int: maxUsers
}

object Role {
    Analyst
    Visualizer
    Manager
}

object Project {
    <u>string: projectId
    string: projectName
    string: projectDescription
    License: license
}

object Task {
    <u>string: taskId
    string: taskName
    string: taskDescription
    TaskStatus: taskStatus
    Project: project
}

object TaskStatus {
    ToDo
    InProgress
    Completed
}

object Sector {
    <u>string: sectorId
    string: sectorName
}

object Company {
    <u>string: companyId
    string: companyName
    string: companyDescription
    string: country
}

object DataProvider {
    <u>string: dataProviderId
    string: dataProviderName
}

object ProviderAlias {
    string: providerAliasId
    string: statementId
    <u>string: providerAliasName
    <u>string: statementId
}

object Functionality {
    <u>string: functionalityId
    string: functionalityName
    string: functionalityDescription
}

object Statement {
    <u>string: statementId
    string: statementName
    string: statementDescription
    StatementType: statementType
    number: value
    number: fiscalYear

}

object StatementType {
    TOTAL
    SUBTOTAL
    ITEM
    SUBITEM
}

object Ratios {
    <u>string: ratioId
    string: ratioId
    string: ratioName
    TUnit: unit
    number: value
    number: year
}

object TUnit {
    PERCENTAGE
    NUMBER
    None
}

object Hypothesis {
    <u>string: hypothesisId
    string: hypothesisName
}

User "*" -- "1" License: "Has"
User "*" -- "*" Project: "Has"
Project "*" -- "*" Task: "Has"
Project "*" -- "*" Company: "Analyze"
Company "*" -- "1" Sector: "Belongs to"
Company "*" -- "*" Functionality: "Has"
Company "*" -- "*" Statement: "Has"
Company "*" -- "*" Ratios: "Has"
Functionality "*" -- "*" Hypothesis: "Has"
User "*" -- "*" Functionality: "Has access to"
DataProvider "*" -- "*" Statement: "Provides"
(DataProvider, Statement) "*" . "*" ProviderAlias




' Restricciones Textuales
' Clave primaria de User(userId), License(licenseId), Role(roleId), Project(projectId), Task(taskId), Sector(sectorId), Company(companyId), Functionality(functionalityId), Statement(statementId), Ratios(ratioId), Hypothesis(hypothesisId)
' 2 En una licencia no puede superar el numero de proyectos maximos y el numero de usuarios maximos
' 3 Un usuario solo puede tener una licencia
' 4 Un usuario puede tener varios roles segun el proyecto en el que esté trabajando
' 5 Solamente la funcionalidad 'DCF' tiene hipotesis
' 6 Un usuario puede acceder a diferentes funcionalidades según su rol

@enduml