@startuml "Modelo Conceptual Chatbot"

object Chat {
    <u>chatId: string
    chatName: string
}

object Message {
    <u>messageId: string
    userMessage: string
    promptMessage: string
    date: data
    usefulness: USEFULNESS
}

object PDF {
    <u>pdfId: string
    pdfName: string
    pdfContent: string
    embeddings: numbers
}

object USEFULNESS {
    USEFUL
    NOTUSEFUL
    NOTRATED
}

Chat "1" -- "*" Message : contains

@enduml