@startuml "ModeloConceptualAccouRateFrontend"

object User {
    <u> userId: string
    username: string
    password: string
    email: string
    role: Role
}

object License {
    <u> licenseId: string
    licenseName: string
    maxProjects: int
    maxUsers: int
}

object Role {
    Analyst
    Visualizer
    Manager
}

object Project {
    <u> projectId: string
    projectName: string
    projectDescription: string
}

object Task {
    <u> taskId: string
    taskName: string
    taskDescription: string
    taskStatus: TaskStatus
}

object TaskStatus {
    ToDo
    InProgress
    Completed
}

object Sector {
    <u> sectorId: string
    sectorName: string
}

object Company {
    <u> companyId: string
    companyName: string
    companyDescription: string
    country: string
}

object DataProvider {
    <u> dataProviderId: string
    dataProviderName: string
}

object ProviderAlias {
    <u> providerAliasId: string
    statementId: string
}

object Functionality {
    <u> functionalityId: string
    functionalityName: string
    functionalityDescription: string
}

object Statement {
    <u> statementId: string
    statementName: string
    statementDescription: string
    statementType: StatementType
    value: number
    fiscalYear: number
}

object StatementType {
    TOTAL
    SUBTOTAL
    ITEM
    SUBITEM
}

object Ratios {
    <u> ratioId: string
    ratioName: string
    unit: TUnit
    value: number
    year: number
}

object TUnit {
    PERCENTAGE
    NUMBER
    None
}

object Hypothesis {
    <u> hypothesisId: string
    hypothesisName: string
}

User "*" -- "1" License: "Has"
User "*" -- "*" Project: "Has"
Project "*" -- "1" License: "Belongs to" 
Project "*" -- "*" Task: "Has"
Project "*" -- "*" Company: "Analyze"
Company "*" -- "1" Sector: "Belongs to"
Company "*" -- "*" Functionality: "Has"
Company "*" -- "*" Statement: "Has"
Company "*" -- "*" Ratios: "Has"
Functionality "*" -- "*" Hypothesis: "Has"
User "*" -- "*" Functionality: "Has access to"
DataProvider "*" -- "*" Statement: "Provides"
(DataProvider, Statement) "*" . "*" ProviderAlias




' Restricciones Textuales
' Clave primaria de User(userId), License(licenseId), Role(roleId), Project(projectId), Task(taskId), Sector(sectorId), Company(companyId), Functionality(functionalityId), Statement(statementId), Ratios(ratioId), Hypothesis(hypothesisId)
' 2 En una licencia no puede superar el numero de proyectos maximos y el numero de usuarios maximos
' 3 Un usuario solo puede tener una licencia
' 4 Un usuario puede tener varios roles segun el proyecto en el que esté trabajando
' 5 Solamente la funcionalidad 'DCF' tiene hipotesis
' 6 Un usuario puede acceder a diferentes funcionalidades según su rol

@enduml